/*
 * Copyright (c) 2020 Bouffalolab.
 *
 * This file is part of
 *     *** Bouffalolab Software Dev Kit ***
 *      (see www.bouffalolab.com).
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of Bouffalo Lab nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*error code definition*/
typedef enum tag_bootrom_error_code_t
{
    BFLB_BOOTROM_SUCCESS=0x00,
    /*flash*/
    BFLB_BOOTROM_FLASH_INIT_ERROR=0x0001,
    BFLB_BOOTROM_FLASH_ERASE_PARA_ERROR=0x0002,
    BFLB_BOOTROM_FLASH_ERASE_ERROR=0x0003,
    BFLB_BOOTROM_FLASH_WRITE_PARA_ERROR=0x0004,
    BFLB_BOOTROM_FLASH_WRITE_ADDR_ERROR=0x0005,
    BFLB_BOOTROM_FLASH_WRITE_ERROR=0x0006,
    BFLB_BOOTROM_FLASH_BOOT_PARA=0x0007,
    /*cmd*/
    BFLB_BOOTROM_CMD_ID_ERROR =0x0101,
    BFLB_BOOTROM_CMD_LEN_ERROR=0x0102,
    BFLB_BOOTROM_CMD_CRC_ERROR=0x0103,
    BFLB_BOOTROM_CMD_SEQ_ERROR=0x0104,
    /*image*/
    BFLB_BOOTROM_IMG_BOOTHEADER_LEN_ERROR=0x0201,
    BFLB_BOOTROM_IMG_BOOTHEADER_NOT_LOAD_ERROR=0x0202,
    BFLB_BOOTROM_IMG_BOOTHEADER_MAGIC_ERROR=0x0203,
    BFLB_BOOTROM_IMG_BOOTHEADER_CRC_ERROR=0x0204,
    BFLB_BOOTROM_IMG_BOOTHEADER_ENCRYPT_NOTFIT=0x0205,
    BFLB_BOOTROM_IMG_BOOTHEADER_SIGN_NOTFIT=0x0206,
    BFLB_BOOTROM_IMG_SEGMENT_CNT_ERROR=0x0207,
    BFLB_BOOTROM_IMG_AES_IV_LEN_ERROR=0x0208,
    BFLB_BOOTROM_IMG_AES_IV_CRC_ERROR=0x0209,
    BFLB_BOOTROM_IMG_PK_LEN_ERROR=0x020a,
    BFLB_BOOTROM_IMG_PK_CRC_ERROR=0x020b,
    BFLB_BOOTROM_IMG_PK_HASH_ERROR=0x020c,
    BFLB_BOOTROM_IMG_SIGNATURE_LEN_ERROR=0x020d,
    BFLB_BOOTROM_IMG_SIGNATURE_CRC_ERROR=0x020e,
    BFLB_BOOTROM_IMG_SECTIONHEADER_LEN_ERROR=0x020f,
    BFLB_BOOTROM_IMG_SECTIONHEADER_CRC_ERROR=0x0210,
    BFLB_BOOTROM_IMG_SECTIONHEADER_DST_ERROR=0x0211,
    BFLB_BOOTROM_IMG_SECTIONDATA_LEN_ERROR=0x0212,
    BFLB_BOOTROM_IMG_SECTIONDATA_DEC_ERROR=0x0213,
    BFLB_BOOTROM_IMG_SECTIONDATA_TLEN_ERROR=0x0214,
    BFLB_BOOTROM_IMG_SECTIONDATA_CRC_ERROR=0x0215,
    BFLB_BOOTROM_IMG_HALFBAKED_ERROR=0x0216,
    BFLB_BOOTROM_IMG_HASH_ERROR=0x0217,
    BFLB_BOOTROM_IMG_SIGN_PARSE_ERROR=0x0218,
    BFLB_BOOTROM_IMG_SIGN_ERROR=0x0219,
    BFLB_BOOTROM_IMG_DEC_ERROR=0x021a,
    BFLB_BOOTROM_IMG_ALL_INVALID_ERROR=0x021b,
    /*IF*/
    BFLB_BOOTROM_IF_RATE_LEN_ERROR=0x0301,
    BFLB_BOOTROM_IF_RATE_PARA_ERROR=0x0302,
    BFLB_BOOTROM_IF_PASSWORDERROR=0x0303,
    BFLB_BOOTROM_IF_PASSWORDCLOSE=0x0304,
    /*MISC*/
    BFLB_BOOTROM_PLL_ERROR=0xfffc,
    BFLB_BOOTROM_INVASION_ERROR=0xfffd,
    BFLB_BOOTROM_POLLING=0xfffe,
    BFLB_BOOTROM_FAIL=0xffff,
} bootrom_error_code_t;

typedef enum tag_eflash_loader_error_code_t
{
    BFLB_EFLASH_LOADER_SUCCESS=0x00,
    /*flash*/
    BFLB_EFLASH_LOADER_FLASH_INIT_ERROR=0x0001,
    BFLB_EFLASH_LOADER_FLASH_ERASE_PARA_ERROR=0x0002,
    BFLB_EFLASH_LOADER_FLASH_ERASE_ERROR=0x0003,
    BFLB_EFLASH_LOADER_FLASH_WRITE_PARA_ERROR=0x0004,
    BFLB_EFLASH_LOADER_FLASH_WRITE_ADDR_ERROR=0x0005,
    BFLB_EFLASH_LOADER_FLASH_WRITE_ERROR=0x0006,
    BFLB_EFLASH_LOADER_FLASH_BOOT_PARA_ERROR=0x0007,
    BFLB_EFLASH_LOADER_FLASH_SET_PARA_ERROR=0x0008,
    BFLB_EFLASH_LOADER_FLASH_READ_STATUS_REG_ERROR=0x0009,
    BFLB_EFLASH_LOADER_FLASH_WRITE_STATUS_REG_ERROR=0x000A,
    /*cmd*/
    BFLB_EFLASH_LOADER_CMD_ID_ERROR =0x0101,
    BFLB_EFLASH_LOADER_CMD_LEN_ERROR=0x0102,
    BFLB_EFLASH_LOADER_CMD_CRC_ERROR=0x0103,
    BFLB_EFLASH_LOADER_CMD_SEQ_ERROR=0x0104,
    /*image*/
    BFLB_EFLASH_LOADER_IMG_BOOTHEADER_LEN_ERROR=0x0201,
    BFLB_EFLASH_LOADER_IMG_BOOTHEADER_NOT_LOAD_ERROR=0x0202,
    BFLB_EFLASH_LOADER_IMG_BOOTHEADER_MAGIC_ERROR=0x0203,
    BFLB_EFLASH_LOADER_IMG_BOOTHEADER_CRC_ERROR=0x0204,
    BFLB_EFLASH_LOADER_IMG_BOOTHEADER_ENCRYPT_NOTFIT=0x0205,
    BFLB_EFLASH_LOADER_IMG_BOOTHEADER_SIGN_NOTFIT=0x0206,
    BFLB_EFLASH_LOADER_IMG_SEGMENT_CNT_ERROR=0x0207,
    BFLB_EFLASH_LOADER_IMG_AES_IV_LEN_ERROR=0x0208,
    BFLB_EFLASH_LOADER_IMG_AES_IV_CRC_ERROR=0x0209,
    BFLB_EFLASH_LOADER_IMG_PK_LEN_ERROR=0x020a,
    BFLB_EFLASH_LOADER_IMG_PK_CRC_ERROR=0x020b,
    BFLB_EFLASH_LOADER_IMG_PK_HASH_ERROR=0x020c,
    BFLB_EFLASH_LOADER_IMG_SIGNATURE_LEN_ERROR=0x020d,
    BFLB_EFLASH_LOADER_IMG_SIGNATURE_CRC_ERROR=0x020e,
    BFLB_EFLASH_LOADER_IMG_SECTIONHEADER_LEN_ERROR=0x020f,
    BFLB_EFLASH_LOADER_IMG_SECTIONHEADER_CRC_ERROR=0x0210,
    BFLB_EFLASH_LOADER_IMG_SECTIONHEADER_DST_ERROR=0x0211,
    BFLB_EFLASH_LOADER_IMG_SECTIONDATA_LEN_ERROR=0x0212,
    BFLB_EFLASH_LOADER_IMG_SECTIONDATA_DEC_ERROR=0x0213,
    BFLB_EFLASH_LOADER_IMG_SECTIONDATA_TLEN_ERROR=0x0214,
    BFLB_EFLASH_LOADER_IMG_SECTIONDATA_CRC_ERROR=0x0215,
    BFLB_EFLASH_LOADER_IMG_HALFBAKED_ERROR=0x0216,
    BFLB_EFLASH_LOADER_IMG_HASH_ERROR=0x0217,
    BFLB_EFLASH_LOADER_IMG_SIGN_PARSE_ERROR=0x0218,
    BFLB_EFLASH_LOADER_IMG_SIGN_ERROR=0x0219,
    BFLB_EFLASH_LOADER_IMG_DEC_ERROR=0x021a,
    BFLB_EFLASH_LOADER_IMG_ALL_INVALID_ERROR=0x021b,
    /*IF*/
    BFLB_EFLASH_LOADER_IF_RATE_LEN_ERROR=0x0301,
    BFLB_EFLASH_LOADER_IF_RATE_PARA_ERROR=0x0302,
    BFLB_EFLASH_LOADER_IF_PASSWORDERROR=0x0303,
    BFLB_EFLASH_LOADER_IF_PASSWORDCLOSE=0x0304,
    /*MISC*/
    BFLB_EFLASH_LOADER_PLL_ERROR=0xfffc,
    BFLB_EFLASH_LOADER_INVASION_ERROR=0xfffd,
    BFLB_EFLASH_LOADER_POLLING=0xfffe,
    BFLB_EFLASH_LOADER_FAIL=0xffff,
} eflash_loader_error_code_t;
